name: Tests (Linux)

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python }} (GEOS ${{ matrix.geos }}, numpy ${{ matrix.numpy || 'not installed' }})
    # runs-on: ubuntu-latest
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # 2015
          - python: 3.5
            geos: 3.5.2
            numpy: 1.13.3
          # 2017
          - python: 3.6
            geos: 3.6.4
            numpy: 1.13.3
          # 2018
          - python: 3.7
            geos: 3.7.3
            numpy: 1.15.4
          # 2019
          - python: 3.8
            geos: 3.8.1
            numpy: 1.17.5
          # 2020
          - python: 3.9
            geos: 3.9.1
            numpy: 1.19.5
          # dev
          - python: 3.9
            geos: master

    env:
      GEOS_VERSION: ${{ matrix.geos }}
      GEOS_INSTALL: ${{ github.workspace }}/geosinstall/geos-${{ matrix.geos }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache GEOS and pip packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-geos-${{ matrix.geos }}
          path: |
            ~/.cache/pip
            ${{ github.workspace }}/geosinstall

      - name: Install GEOS
        shell: bash
        run: |
          ./ci/install_geos.sh
          cd ${{ github.workspace }}

      - name: Set environment variables for PyGEOS installation
        shell: bash
        run: |
          echo "GEOS_CONFIG=$GEOS_INSTALL/bin/geos-config" >> $GITHUB_ENV

      - name: Install python dependencies
        shell: bash
        run: |
          pip install --disable-pip-version-check --upgrade pip
          pip install --upgrade wheel
          pip install git+https://github.com/pygeos/pygeos.git -v
          if [ "$GEOS_VERSION" = "master" ]; then
            pip install --upgrade --pre Cython numpy;
          elif [ -n "${{ matrix.numpy }}" ]; then
            pip install --upgrade numpy==${{ matrix.numpy }};
          else
            pip uninstall --yes numpy;
          fi
          pip install --upgrade coveralls pytest-cov pytest
          pip list

      - name: Set environment variables
        shell: bash
        run: |
          echo "LD_LIBRARY_PATH=$GEOS_INSTALL/lib" >> $GITHUB_ENV
          echo $GEOS_INSTALL/bin >> $GITHUB_PATH

      - name: Build and install Shapely
        shell: bash
        run: |
          pip install -v -e .

      - name: Overview of the Python environment (pip list)
        shell: bash
        run: |
          pip list

      - name: Run tests
        shell: bash
        continue-on-error: ${{ matrix.geos == 'master' }}
        run: |
          python -c "from shapely import geos; print(geos.geos_version_string)"
          python -m pytest --cov shapely --cov-report term-missing

      - name: Run doctests
        if: ${{ matrix.python == '3.8' }}
        shell: bash
        run: |
          python -m pytest shapely --doctest-modules

      - name: Upload coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
        shell: bash
        run: |
          coveralls --service=github || echo "!! intermittent coveralls failure"

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish || echo "!! intermittent coveralls failure"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
